-- Auto-generated by Matugen
-- TokyoNight with Material You color palette (blended)

-- Helper function to blend colors
local function mix(color1, color2, weight)
	local function hexToRgb(hex)
		hex = hex:gsub("#", "")
		return tonumber("0x" .. hex:sub(1, 2)), tonumber("0x" .. hex:sub(3, 4)), tonumber("0x" .. hex:sub(5, 6))
	end

	local r1, g1, b1 = hexToRgb(color1)
	local r2, g2, b2 = hexToRgb(color2)

	local r = math.floor(r1 * (1 - weight) + r2 * weight)
	local g = math.floor(g1 * (1 - weight) + g2 * weight)
	local b = math.floor(b1 * (1 - weight) + b2 * weight)

	return string.format("#%02x%02x%02x", r, g, b)
end

require("tokyonight").setup({
	style = "night",
	transparent = true,
	terminal_colors = true,
	styles = {
		sidebars = "transparent",
		floats = "transparent",
	},
	dim_inactive = false,
	lualine_bold = true,

	---@param colors ColorScheme
	on_colors = function(colors)
		-- Background colors (use matugen directly for backgrounds)
		colors.bg = "{{colors.background.default.hex}}"
		colors.bg_dark = "{{colors.surface_container_lowest.default.hex}}"
		colors.bg_dark1 = "{{colors.surface_container_lowest.default.hex}}"
		colors.bg_float = "{{colors.surface_container.default.hex}}"
		colors.bg_highlight = "{{colors.surface_container.default.hex}}"
		colors.bg_popup = "{{colors.surface_container.default.hex}}"
		colors.bg_search = "{{colors.primary_container.default.hex}}"
		colors.bg_sidebar = "{{colors.surface_container_lowest.default.hex}}"
		colors.bg_statusline = "{{colors.surface_container.default.hex}}"
		colors.bg_visual = "{{colors.primary_container.default.hex}}"

		-- Foreground colors (use matugen directly)
		colors.fg = "{{colors.on_surface.default.hex}}"
		colors.fg_dark = "{{colors.on_surface_variant.default.hex}}"
		colors.fg_float = "{{colors.on_surface.default.hex}}"
		colors.fg_gutter = "{{colors.outline_variant.default.hex}}"
		colors.fg_sidebar = "{{colors.on_surface.default.hex}}"

		-- Border colors
		colors.border = "{{colors.outline.default.hex}}"
		colors.border_highlight = "{{colors.primary.default.hex}}"

		-- Syntax colors - Blue family (blend with primary)
		colors.blue = mix("#7aa2f7", "{{colors.primary.default.hex}}", 0.8)
		colors.blue0 = mix("#3d59a1", "{{colors.primary.default.hex}}", 0.8)
		colors.blue1 = mix("#2ac3de", "{{colors.primary.default.hex}}", 0.8)
		colors.blue2 = mix("#0db9d7", "{{colors.primary.default.hex}}", 0.8)
		colors.blue5 = mix("#89ddff", "{{colors.primary.default.hex}}", 0.8)
		colors.blue6 = mix("#b4f9f8", "{{colors.primary.default.hex}}", 0.8)
		colors.blue7 = mix("#394b70", "{{colors.primary.default.hex}}", 0.8)
		colors.cyan = mix("#7dcfff", "{{colors.primary.default.hex}}", 0.8)

		-- Syntax colors - Purple/Magenta family (blend with secondary)
		colors.magenta = mix("#bb9af7", "{{colors.primary.default.hex}}", 0.5)
		colors.magenta2 = mix("#ff007c", "{{colors.primary.default.hex}}", 0.5)
		colors.purple = mix("#9d7cd8", "{{colors.primary.default.hex}}", 0.5)

		-- Syntax colors - Orange/Yellow family (blend with tertiary)
		colors.orange = mix("#ff9e64", "{{colors.tertiary.default.hex}}", 0.8)
		colors.yellow = mix("#e0af68", "{{colors.tertiary.default.hex}}", 0.8)

		-- Syntax colors - Red family (blend with error)
		colors.red = mix("#f7768e", "{{colors.error.default.hex}}", 0.5)
		colors.red1 = mix("#db4b4b", "{{colors.error.default.hex}}", 0.5)

		-- Syntax colors - Green/Teal family (blend with primary)
		colors.green = mix("#9ece6a", "{{colors.primary.default.hex}}", 0.5)
		colors.green1 = mix("#73daca", "{{colors.primary.default.hex}}", 0.5)
		colors.green2 = mix("#41a6b5", "{{colors.primary.default.hex}}", 0.5)
		colors.teal = mix("#1abc9c", "{{colors.primary.default.hex}}", 0.5)

		-- UI colors
		colors.comment = "{{colors.outline.default.hex}}"
		colors.dark3 = "{{colors.outline_variant.default.hex}}"
		colors.dark5 = "{{colors.outline.default.hex}}"
		colors.terminal_black = "{{colors.surface_container_highest.default.hex}}"
		colors.black = "{{colors.surface_container_lowest.default.hex}}"

		-- Git colors (blend)
		colors.git = {
			add = mix("#9ece6a", "{{colors.primary.default.hex}}", 0.15),
			change = mix("#e0af68", "{{colors.tertiary.default.hex}}", 0.15),
			delete = mix("#db4b4b", "{{colors.error.default.hex}}", 0.15),
			ignore = "{{colors.outline_variant.default.hex}}",
			text = mix("#58A6FF", "{{colors.primary.default.hex}}", 0.15),
		}

		local bg = "{{colors.background.default.hex}}"

		-- Diff colors (blend)
		colors.diff = {
			add = mix(colors.git.add, bg, 0.7),
			change = mix(colors.git.change, bg, 0.7),
			delete = mix(colors.git.delete, bg, 0.7),
			text = mix(colors.git.text, bg, 0.7),
		}

		-- Diagnostics (blend)
		colors.error = mix("#db4b4b", "{{colors.error.default.hex}}", 0.5)
		colors.warning = mix("#e0af68", "{{colors.primary.default.hex}}", 0.5)
		colors.info = mix("#0db9d7", "{{colors.primary.default.hex}}", 0.5)
		colors.hint = mix("#1abc9c", "{{colors.primary.default.hex}}", 0.5)
		colors.todo = mix("#7aa2f7", "{{colors.primary.default.hex}}", 0.5)

		-- Rainbow colors for brackets etc (blend)
		colors.rainbow = {
			mix("#7aa2f7", "{{colors.primary.default.hex}}", 0.5),
			mix("#e0af68", "{{colors.tertiary.default.hex}}", 0.5),
			mix("#9ece6a", "{{colors.primary.default.hex}}", 0.5),
			mix("#1abc9c", "{{colors.primary.default.hex}}", 0.5),
			mix("#bb9af7", "{{colors.secondary.default.hex}}", 0.5),
			mix("#9d7cd8", "{{colors.secondary.default.hex}}", 0.5),
			mix("#ff9e64", "{{colors.tertiary.default.hex}}", 0.5),
			mix("#f7768e", "{{colors.error.default.hex}}", 0.5),
		}

		-- Terminal colors (blend)
		colors.terminal = {
			black = "{{colors.surface_container_lowest.default.hex}}",
			black_bright = "{{colors.surface_container_highest.default.hex}}",
			blue = mix("#7aa2f7", "{{colors.primary.default.hex}}", 0.5),
			blue_bright = mix("#8db0ff", "{{colors.primary.default.hex}}", 0.5),
			cyan = mix("#7dcfff", "{{colors.primary.default.hex}}", 0.5),
			cyan_bright = mix("#a4daff", "{{colors.primary.default.hex}}", 0.5),
			green = mix("#9ece6a", "{{colors.primary.default.hex}}", 0.5),
			green_bright = mix("#9fe044", "{{colors.primary.default.hex}}", 0.5),
			magenta = mix("#bb9af7", "{{colors.secondary.default.hex}}", 0.5),
			magenta_bright = mix("#c7a9ff", "{{colors.secondary.default.hex}}", 0.5),
			red = mix("#f7768e", "{{colors.error.default.hex}}", 0.5),
			red_bright = mix("#ff899d", "{{colors.error.default.hex}}", 0.5),
			white = "{{colors.on_surface_variant.default.hex}}",
			white_bright = "{{colors.on_surface.default.hex}}",
			yellow = mix("#e0af68", "{{colors.tertiary.default.hex}}", 0.5),
			yellow_bright = mix("#faba4a", "{{colors.tertiary.default.hex}}", 0.5),
		}

		-- None color for transparent
		colors.none = "NONE"
	end,

	---@param hl tokyonight.Highlights
	---@param c ColorScheme
	on_highlights = function(hl, c)
		-- Transparent backgrounds
		hl.Normal = { fg = c.fg, bg = "NONE" }
		hl.NormalNC = { fg = c.fg, bg = "NONE" }
		hl.NormalSB = { fg = c.fg, bg = "NONE" }
		hl.SignColumn = { bg = "NONE" }
		hl.LineNr = { fg = c.fg_gutter, bg = "NONE" }
		hl.CursorLineNr = { fg = c.blue, bg = "NONE", bold = true }
		hl.EndOfBuffer = { fg = c.bg, bg = "NONE" }
		hl.Folded = { fg = c.comment, bg = "NONE" }
		hl.WinSeparator = { fg = c.border, bg = "NONE" }

		-- NonText
		hl.NonText = { fg = "{{colors.outline.default.hex}}" }
		hl.LspInlayHint = { fg = "{{colors.outline.default.hex}}", bg = "NONE" }

		-- Floating Windows
		hl.NormalFloat = { fg = c.fg, bg = "NONE" }
		hl.FloatBorder = { fg = c.blue, bg = "NONE" }
		hl.FloatTitle = { fg = c.blue, bg = "NONE" }

		-- Completion menu
		hl.Pmenu = { fg = c.fg, bg = "NONE" }
		hl.PmenuSel = { bg = "{{colors.primary_container.default.hex}}" }
		hl.PmenuSbar = { bg = "NONE" }
		hl.PmenuThumb = { bg = c.border }

		-- Visual selection
		hl.Visual = { bg = "{{colors.primary_container.default.hex}}" }
		hl.VisualNOS = { bg = "{{colors.primary_container.default.hex}}" }

		-- Search
		hl.Search = { fg = "{{colors.on_primary.default.hex}}", bg = c.blue }
		hl.IncSearch = { fg = "{{colors.on_tertiary.default.hex}}", bg = c.orange }
		hl.CurSearch = { fg = "{{colors.on_primary.default.hex}}", bg = c.blue }

		-- Cursor line
		hl.CursorLine = { bg = "{{colors.surface_container.default.hex}}" }

		-- Blink.cmp
		hl.BlinkCmpDoc = { fg = c.fg, bg = "NONE" }
		hl.BlinkCmpDocBorder = { fg = c.blue, bg = "NONE" }
		hl.BlinkCmpGhostText = { fg = c.comment }
		hl.BlinkCmpLabel = { fg = c.fg, bg = "NONE" }
		hl.BlinkCmpLabelDeprecated = { fg = c.comment, bg = "NONE", strikethrough = true }
		hl.BlinkCmpLabelMatch = { fg = c.blue, bg = "NONE" }
		hl.BlinkCmpMenu = { fg = c.fg, bg = "NONE" }
		hl.BlinkCmpMenuBorder = { fg = c.blue, bg = "NONE" }
		hl.BlinkCmpSignatureHelp = { fg = c.fg, bg = "NONE" }
		hl.BlinkCmpSignatureHelpBorder = { fg = c.blue, bg = "NONE" }

		-- Noice
		hl.NoiceCmdline = { bg = "NONE" }
		hl.NoiceCmdlinePopup = { bg = "NONE" }
		hl.NoicePopup = { bg = "NONE" }
		hl.NoicePopupmenu = { bg = "NONE" }
		hl.NoiceScrollbar = { bg = "NONE" }
		hl.NoiceCmdlinePopupBorder = { fg = c.blue, bg = "NONE" }
		hl.NoiceCmdlinePopupBorderSearch = { fg = c.orange, bg = "NONE" }
		hl.NoiceCmdlinePopupTitle = { fg = c.blue, bg = "NONE" }
		hl.NoiceCmdlineIcon = { fg = c.blue, bg = "NONE" }
		hl.NoiceCmdlineIconSearch = { fg = c.orange, bg = "NONE" }
		hl.NoicePopupBorder = { fg = c.blue, bg = "NONE" }
		hl.NoicePopupmenuBorder = { fg = c.blue, bg = "NONE" }

		-- Snacks Notifier
		hl.SnacksNotifierDebug = { fg = c.fg, bg = "NONE" }
		hl.SnacksNotifierBorderDebug = { fg = c.purple, bg = "NONE" }
		hl.SnacksNotifierIconDebug = { fg = c.purple }
		hl.SnacksNotifierTitleDebug = { fg = c.purple }
		hl.SnacksNotifierError = { fg = c.fg, bg = "NONE" }
		hl.SnacksNotifierBorderError = { fg = c.error, bg = "NONE" }
		hl.SnacksNotifierIconError = { fg = c.error }
		hl.SnacksNotifierTitleError = { fg = c.error }
		hl.SnacksNotifierInfo = { fg = c.fg, bg = "NONE" }
		hl.SnacksNotifierBorderInfo = { fg = c.info, bg = "NONE" }
		hl.SnacksNotifierIconInfo = { fg = c.info }
		hl.SnacksNotifierTitleInfo = { fg = c.info }
		hl.SnacksNotifierTrace = { fg = c.fg, bg = "NONE" }
		hl.SnacksNotifierBorderTrace = { fg = c.purple, bg = "NONE" }
		hl.SnacksNotifierIconTrace = { fg = c.purple }
		hl.SnacksNotifierTitleTrace = { fg = c.purple }
		hl.SnacksNotifierWarn = { fg = c.fg, bg = "NONE" }
		hl.SnacksNotifierBorderWarn = { fg = c.warning, bg = "NONE" }
		hl.SnacksNotifierIconWarn = { fg = c.warning }
		hl.SnacksNotifierTitleWarn = { fg = c.warning }

		-- Snacks Dashboard
		hl.SnacksDashboardDesc = { fg = c.info }
		hl.SnacksDashboardFooter = { fg = c.blue }
		hl.SnacksDashboardHeader = { fg = c.blue }
		hl.SnacksDashboardIcon = { fg = c.blue }
		hl.SnacksDashboardKey = { fg = c.orange }
		hl.SnacksDashboardSpecial = { fg = c.purple }
		hl.SnacksDashboardDir = { fg = c.comment }

		-- Picker
		hl.SnacksPickerInputBorder = { fg = c.blue, bg = "NONE" }
		hl.SnacksPickerInputTitle = { fg = c.blue, bg = "NONE" }
		hl.SnacksPickerTitle = { fg = c.blue, bg = "NONE" }
		hl.SnacksPickerBoxTitle = { fg = c.blue, bg = "NONE" }
		hl.SnacksPickerSelected = { fg = c.blue }
		hl.SnacksPickerToggle = "SnacksProfilerBadgeInfo"
		hl.SnacksPickerPickWinCurrent = { fg = c.fg, bg = c.blue, bold = true }
		hl.SnacksPickerPickWin = { fg = c.fg, bg = c.bg_search, bold = true }
		hl.SnacksGhLabel = { fg = c.blue1, bold = true }

		-- Blink.pairs rainbow brackets
		hl.BlinkPairsOrange = { fg = c.orange }
		hl.BlinkPairsPurple = { fg = c.purple }
		hl.BlinkPairsBlue = { fg = c.blue }
		hl.BlinkPairsUnmatched = { fg = c.red }
		hl.BlinkPairsMatchParen = { fg = "{{colors.on_primary.default.hex}}", bg = c.blue, bold = true }

		-- Mini.icons colors (blended with matugen theme)
		local mini_azure = mix("#007FFF", "{{colors.primary.default.hex}}", 0.7)
		local mini_blue = mix("#0000FF", "{{colors.primary.default.hex}}", 0.7)
		local mini_cyan = mix("#00FFFF", "{{colors.primary.default.hex}}", 0.7)
		local mini_green = mix("#00FF00", "{{colors.primary.default.hex}}", 0.7)
		local mini_grey = mix("#808080", "{{colors.outline.default.hex}}", 0.7)
		local mini_orange = mix("#FF8800", "{{colors.primary.default.hex}}", 0.7)
		local mini_purple = mix("#8800FF", "{{colors.primary.default.hex}}", 0.7)
		local mini_red = mix("#FF0000", "{{colors.error.default.hex}}", 0.7)
		local mini_yellow = mix("#FFFF00", "{{colors.primary.default.hex}}", 0.7)

		hl.MiniIconsAzure = { fg = mini_azure }
		hl.MiniIconsBlue = { fg = mini_blue }
		hl.MiniIconsCyan = { fg = mini_cyan }
		hl.MiniIconsGreen = { fg = mini_green }
		hl.MiniIconsGrey = { fg = mini_grey }
		hl.MiniIconsOrange = { fg = mini_orange }
		hl.MiniIconsPurple = { fg = mini_purple }
		hl.MiniIconsRed = { fg = mini_red }
		hl.MiniIconsYellow = { fg = mini_yellow }

		-- Gitsigns highlights
		hl.GitSignsAdd = { fg = c.git.add, bg = "NONE" }
		hl.GitSignsChange = { fg = c.git.change, bg = "NONE" }
		hl.GitSignsDelete = { fg = c.git.delete, bg = "NONE" }
		hl.GitSignsChangedelete = { fg = c.git.change, bg = "NONE" }
		hl.GitSignsTopdelete = { fg = c.git.delete, bg = "NONE" }
		hl.GitSignsUntracked = { fg = c.git.add, bg = "NONE" }
		hl.GitSignsAddNr = { fg = c.git.add, bg = "NONE" }
		hl.GitSignsChangeNr = { fg = c.git.change, bg = "NONE" }
		hl.GitSignsDeleteNr = { fg = c.git.delete, bg = "NONE" }
		hl.GitSignsAddLn = { bg = c.diff.add }
		hl.GitSignsChangeLn = { bg = c.diff.change }
		hl.GitSignsDeleteLn = { bg = c.diff.delete }

		hl.Diffadded = { link = "GitSignsAdd" }
		hl.Diffchanged = { link = "GitSignsChange" }
		hl.Diffremoved = { link = "GitSignsDelete" }

		-- Diagnostic colors
		hl.DiagnosticError = { fg = c.error, bg = "NONE" }
		hl.DiagnosticWarn = { fg = c.warning, bg = "NONE" }
		hl.DiagnosticInfo = { fg = c.info, bg = "NONE" }
		hl.DiagnosticHint = { fg = c.hint, bg = "NONE" }
		hl.DiagnosticVirtualTextError = { fg = c.error, bg = mix(c.error, c.bg, 0.85) }
		hl.DiagnosticVirtualTextWarn = { fg = c.warning, bg = mix(c.warning, c.bg, 0.85) }
		hl.DiagnosticVirtualTextInfo = { fg = c.info, bg = mix(c.info, c.bg, 0.85) }
		hl.DiagnosticVirtualTextHint = { fg = c.hint, bg = mix(c.hint, c.bg, 0.90) }
		hl.DiagnosticUnderlineError = { undercurl = true, sp = c.error }
		hl.DiagnosticUnderlineWarn = { undercurl = true, sp = c.warning }
		hl.DiagnosticUnderlineInfo = { undercurl = true, sp = c.info }
		hl.DiagnosticUnderlineHint = { undercurl = true, sp = c.hint }
		hl.DiagnosticSignError = { fg = c.error, bg = "NONE" }
		hl.DiagnosticSignWarn = { fg = c.warning, bg = "NONE" }
		hl.DiagnosticSignInfo = { fg = c.info, bg = "NONE" }
		hl.DiagnosticSignHint = { fg = c.hint, bg = "NONE" }
		hl.DiagnosticSignerror = { link = "DiagnosticError" }
		hl.DiagnosticSignwarn = { link = "DiagnosticWarn" }
		hl.DiagnosticSigninfo = { link = "DiagnosticInfo" }
		hl.DiagnosticSignhint = { link = "DiagnosticHint" }

		-- Todo-comments colors (blended with matugen theme)
		local todo_fix = mix("#DB4B4B", "{{colors.error.default.hex}}", 0.5)
		local todo_todo = mix("#1ABC9C", "{{colors.secondary.default.hex}}", 0.5)
		local todo_hack = mix("#FF9E64", "{{colors.tertiary.default.hex}}", 0.5)
		local todo_warn = mix("#E0AF68", "{{colors.tertiary.default.hex}}", 0.5)
		local todo_perf = mix("#9D7CD8", "{{colors.secondary.default.hex}}", 0.5)
		local todo_note = mix("#7C3AED", "{{colors.primary.default.hex}}", 0.5)
		local todo_test = mix("#9D7CD8", "{{colors.secondary.default.hex}}", 0.5)

		-- Todo-comments highlight groups
		hl.TodoBgFIX = { fg = "{{colors.on_error.default.hex}}", bg = todo_fix, bold = true }
		hl.TodoBgTODO = { fg = "{{colors.on_secondary.default.hex}}", bg = todo_todo, bold = true }
		hl.TodoBgHACK = { fg = "{{colors.on_tertiary.default.hex}}", bg = todo_hack, bold = true }
		hl.TodoBgWARN = { fg = "{{colors.on_tertiary.default.hex}}", bg = todo_warn, bold = true }
		hl.TodoBgPERF = { fg = "{{colors.on_secondary.default.hex}}", bg = todo_perf, bold = true }
		hl.TodoBgNOTE = { fg = "{{colors.on_primary.default.hex}}", bg = todo_note, bold = true }
		hl.TodoBgTEST = { fg = "{{colors.on_secondary.default.hex}}", bg = todo_test, bold = true }

		hl.TodoFgFIX = { fg = todo_fix }
		hl.TodoFgTODO = { fg = todo_todo }
		hl.TodoFgHACK = { fg = todo_hack }
		hl.TodoFgWARN = { fg = todo_warn }
		hl.TodoFgPERF = { fg = todo_perf }
		hl.TodoFgNOTE = { fg = todo_note }
		hl.TodoFgTEST = { fg = todo_test }

		hl.TodoSignFIX = { fg = todo_fix, bg = "NONE" }
		hl.TodoSignTODO = { fg = todo_todo, bg = "NONE" }
		hl.TodoSignHACK = { fg = todo_hack, bg = "NONE" }
		hl.TodoSignWARN = { fg = todo_warn, bg = "NONE" }
		hl.TodoSignPERF = { fg = todo_perf, bg = "NONE" }
		hl.TodoSignNOTE = { fg = todo_note, bg = "NONE" }
		hl.TodoSignTEST = { fg = todo_test, bg = "NONE" }

		hl.WhichKey = { fg = c.cyan }
		hl.WhichKeyGroup = { fg = c.blue }
		hl.WhichKeyDesc = { fg = c.magenta }
		hl.WhichKeySeparator = { fg = c.comment }
		hl.WhichKeyTitle = { fg = c.blue }
		hl.WhichKeyNormal = { bg = "NONE" }
		hl.WhichKeyValue = { fg = c.dark5 }
	end,

	plugins = {
		all = true,
	},
})

vim.cmd.colorscheme("tokyonight-night")
