# Auto-generated by Matugen - Fish syntax highlighting colors

set -U fish_color_normal #e6e3d5
set -U fish_color_command #cbcb76
set -U fish_color_keyword #a4d0bd
set -U fish_color_quote #cac8a5
set -U fish_color_redirection #a4d0bd
set -U fish_color_end #939182
set -U fish_color_error #ffb4ab
set -U fish_color_param #cac7b6
set -U fish_color_option #cac7b6
set -U fish_color_comment #939182
set -U fish_color_selection --background=#48473a
set -U fish_color_search_match --background=#48473a
set -U fish_color_operator #a4d0bd
set -U fish_color_escape #a4d0bd
set -U fish_color_autosuggestion #939182
set -U fish_color_valid_path --underline
set -U fish_color_cwd #cbcb76
set -U fish_color_user #cac8a5
set -U fish_color_host #a4d0bd
set -U fish_color_cancel #ffb4ab

# Pager colors (tab completion menu)
set -U fish_pager_color_progress #cbcb76
set -U fish_pager_color_prefix #a4d0bd --bold
set -U fish_pager_color_completion #e6e3d5
set -U fish_pager_color_description #939182
set -U fish_pager_color_selected_background --background=#48473a
