# Auto-generated by Matugen - Fish syntax highlighting colors

set -U fish_color_normal #dee3e5
set -U fish_color_command #83d2e5
set -U fish_color_keyword #bdc5eb
set -U fish_color_quote #b2cbd2
set -U fish_color_redirection #bdc5eb
set -U fish_color_end #899295
set -U fish_color_error #ffb4ab
set -U fish_color_param #bfc8cb
set -U fish_color_option #bfc8cb
set -U fish_color_comment #899295
set -U fish_color_selection --background=#3f484b
set -U fish_color_search_match --background=#3f484b
set -U fish_color_operator #bdc5eb
set -U fish_color_escape #bdc5eb
set -U fish_color_autosuggestion #899295
set -U fish_color_valid_path --underline
set -U fish_color_cwd #83d2e5
set -U fish_color_user #b2cbd2
set -U fish_color_host #bdc5eb
set -U fish_color_cancel #ffb4ab

# Pager colors (tab completion menu)
set -U fish_pager_color_progress #83d2e5
set -U fish_pager_color_prefix #bdc5eb --bold
set -U fish_pager_color_completion #dee3e5
set -U fish_pager_color_description #899295
set -U fish_pager_color_selected_background --background=#3f484b
