# Auto-generated by Matugen - Fish syntax highlighting colors

set -U fish_color_normal #dfe4dc
set -U fish_color_command #97d5a5
set -U fish_color_keyword #a2ced9
set -U fish_color_quote #b6ccb8
set -U fish_color_redirection #a2ced9
set -U fish_color_end #8b938a
set -U fish_color_error #ffb4ab
set -U fish_color_param #c1c9bf
set -U fish_color_option #c1c9bf
set -U fish_color_comment #8b938a
set -U fish_color_selection --background=#414941
set -U fish_color_search_match --background=#414941
set -U fish_color_operator #a2ced9
set -U fish_color_escape #a2ced9
set -U fish_color_autosuggestion #8b938a
set -U fish_color_valid_path --underline
set -U fish_color_cwd #97d5a5
set -U fish_color_user #b6ccb8
set -U fish_color_host #a2ced9
set -U fish_color_cancel #ffb4ab

# Pager colors (tab completion menu)
set -U fish_pager_color_progress #97d5a5
set -U fish_pager_color_prefix #a2ced9 --bold
set -U fish_pager_color_completion #dfe4dc
set -U fish_pager_color_description #8b938a
set -U fish_pager_color_selected_background --background=#414941
