# Auto-generated by Matugen - FZF colors for fish
# Source this file in your config.fish

set -gx FZF_DEFAULT_OPTS "\
--color=bg:-1,bg+:#83d2e5,fg:#dee3e5,fg+:#00363f \
--color=hl:#bdc5eb,hl+:#00363f,info:#b2cbd2,marker:#bdc5eb \
--color=prompt:#83d2e5,spinner:#bdc5eb,pointer:#bdc5eb,header:#899295 \
--color=border:#83d2e5,label:#dee3e5,query:#dee3e5 \
--highlight-line --border=bold --prompt='> ' --pointer='▶' --marker='✓'"
