# Auto-generated by Matugen - FZF colors for fish
# Source this file in your config.fish

set -gx FZF_DEFAULT_OPTS "\
--color=bg:-1,bg+:#a0d49b,fg:#e0e4db,fg+:#083910 \
--color=hl:#a1ced5,hl+:#083910,info:#b9ccb4,marker:#a1ced5 \
--color=prompt:#a0d49b,spinner:#a1ced5,pointer:#a1ced5,header:#8c9388 \
--color=border:#a0d49b,label:#e0e4db,query:#e0e4db \
--highlight-line --border=bold --prompt='> ' --pointer='▶' --marker='✓'"
