# Auto-generated by Matugen - FZF colors for fish
# Source this file in your config.fish

set -gx FZF_DEFAULT_OPTS "\
--color=bg:-1,bg+:#cbcb76,fg:#e6e3d5,fg+:#323200 \
--color=hl:#a4d0bd,hl+:#323200,info:#cac8a5,marker:#a4d0bd \
--color=prompt:#cbcb76,spinner:#a4d0bd,pointer:#a4d0bd,header:#939182 \
--color=border:#cbcb76,label:#e6e3d5,query:#e6e3d5 \
--highlight-line --border=bold --prompt='> ' --pointer='▶' --marker='✓'"
