# Auto-generated by Matugen - Fish syntax highlighting colors

set -U fish_color_normal {{colors.on_surface.default.hex}}
set -U fish_color_command {{colors.primary.default.hex}}
set -U fish_color_keyword {{colors.tertiary.default.hex}}
set -U fish_color_quote {{colors.secondary.default.hex}}
set -U fish_color_redirection {{colors.tertiary.default.hex}}
set -U fish_color_end {{colors.outline.default.hex}}
set -U fish_color_error {{colors.error.default.hex}}
set -U fish_color_param {{colors.on_surface_variant.default.hex}}
set -U fish_color_option {{colors.on_surface_variant.default.hex}}
set -U fish_color_comment {{colors.outline.default.hex}}
set -U fish_color_selection --background={{colors.surface_variant.default.hex}}
set -U fish_color_search_match --background={{colors.surface_variant.default.hex}}
set -U fish_color_operator {{colors.tertiary.default.hex}}
set -U fish_color_escape {{colors.tertiary.default.hex}}
set -U fish_color_autosuggestion {{colors.outline.default.hex}}
set -U fish_color_valid_path --underline
set -U fish_color_cwd {{colors.primary.default.hex}}
set -U fish_color_user {{colors.secondary.default.hex}}
set -U fish_color_host {{colors.tertiary.default.hex}}
set -U fish_color_cancel {{colors.error.default.hex}}

# Pager colors (tab completion menu)
set -U fish_pager_color_progress {{colors.primary.default.hex}}
set -U fish_pager_color_prefix {{colors.tertiary.default.hex}} --bold
set -U fish_pager_color_completion {{colors.on_surface.default.hex}}
set -U fish_pager_color_description {{colors.outline.default.hex}}
set -U fish_pager_color_selected_background --background={{colors.surface_variant.default.hex}}
