# Auto-generated by Matugen - FZF colors for fish
# Source this file in your config.fish

set -gx FZF_DEFAULT_OPTS "\
--color=bg:-1,bg+:{{colors.primary.default.hex}},fg:{{colors.on_surface.default.hex}},fg+:{{colors.on_primary.default.hex}} \
--color=hl:{{colors.tertiary.default.hex}},hl+:{{colors.on_primary.default.hex}},info:{{colors.secondary.default.hex}},marker:{{colors.tertiary.default.hex}} \
--color=prompt:{{colors.primary.default.hex}},spinner:{{colors.tertiary.default.hex}},pointer:{{colors.tertiary.default.hex}},header:{{colors.outline.default.hex}} \
--color=border:{{colors.primary.default.hex}},label:{{colors.on_surface.default.hex}},query:{{colors.on_surface.default.hex}} \
--highlight-line --border=bold --prompt='> ' --pointer='▶' --marker='✓'"
