#!/bin/bash
# Sweet Theme Color Variables
# Generated by Matugen

# Dark theme mappings (original -> new)
declare -A DARK_COLORS=(
    # Main colors
    ["#C3C7D1"]="{{colors.on_surface.default.hex}}"
    ["#c3c7d1"]="{{colors.on_surface.default.hex}}"
    ["#161925"]="{{colors.surface.default.hex}}"
    ["#181b28"]="{{colors.surface_container.default.hex}}"
    ["#00D3A7"]="{{colors.primary.default.hex}}"
    ["#00d3a7"]="{{colors.primary.default.hex}}"
    ["#fefefe"]="{{colors.on_primary.default.hex}}"
    ["#6d707b"]="{{colors.outline.default.hex}}"
    ["#171a26"]="{{colors.surface_dim.default.hex}}"
    ["#1a1d2b"]="{{colors.surface_container_low.default.hex}}"
    # Warning/Error/Success
    ["#cc5500"]="{{colors.tertiary.default.hex}}"
    ["#e6133e"]="{{colors.error.default.hex}}"
    ["#0096b1"]="{{colors.secondary.default.hex}}"
    # Additional dark shades
    ["#0f111a"]="{{colors.surface_dim.default.hex}}"
    ["#1c1f2b"]="{{colors.surface_container_high.default.hex}}"
    ["#22252e"]="{{colors.surface_container_highest.default.hex}}"
    ["#cdcdcd"]="{{colors.surface_variant.default.hex}}"
)

# Light theme mappings (original -> new)
declare -A LIGHT_COLORS=(
    # Main colors
    ["#31363d"]="{{colors.on_surface.default.hex}}"
    ["#31363D"]="{{colors.on_surface.default.hex}}"
    ["#e6e6e6"]="{{colors.surface.default.hex}}"
    ["#ebf0f5"]="{{colors.surface_container.default.hex}}"
    ["#00D3A7"]="{{colors.primary.default.hex}}"
    ["#00d3a7"]="{{colors.primary.default.hex}}"
    ["#fefefe"]="{{colors.on_primary.default.hex}}"
    ["#8c8e92"]="{{colors.outline.default.hex}}"
    ["#e8eaec"]="{{colors.surface_dim.default.hex}}"
    ["#e8edf3"]="{{colors.surface_container_low.default.hex}}"
    # Warning/Error/Success
    ["#ff6a00"]="{{colors.tertiary.default.hex}}"
    ["#ed254e"]="{{colors.error.default.hex}}"
    ["#00c1e4"]="{{colors.secondary.default.hex}}"
    # Additional light shades
    ["#cdcdcd"]="{{colors.surface_variant.default.hex}}"
)

THEME_DIR="$HOME/.local/share/themes/Sweet"
BACKUP_DIR="$HOME/.local/share/themes/Sweet-backup"

# Create backup on first run
backup_theme() {
    if [[ ! -d "$BACKUP_DIR" ]]; then
        echo "Creating backup of original Sweet theme..."
        cp -r "$THEME_DIR" "$BACKUP_DIR"
    fi
}

# Restore from backup before applying new colors
restore_from_backup() {
    if [[ -d "$BACKUP_DIR" ]]; then
        echo "Restoring from backup..."
        cp "$BACKUP_DIR/gtk-3.0/gtk.css" "$THEME_DIR/gtk-3.0/gtk.css"
        cp "$BACKUP_DIR/gtk-3.0/gtk-dark.css" "$THEME_DIR/gtk-3.0/gtk-dark.css"
        cp "$BACKUP_DIR/gtk-4.0/gtk.css" "$THEME_DIR/gtk-4.0/gtk.css"
        cp "$BACKUP_DIR/gtk-4.0/gtk-dark.css" "$THEME_DIR/gtk-4.0/gtk-dark.css"
    fi
}

apply_colors() {
    local file="$1"
    local -n colors=$2

    if [[ ! -f "$file" ]]; then
        echo "File not found: $file"
        return 1
    fi

    local tmp_file=$(mktemp)
    cp "$file" "$tmp_file"

    for old_color in "${!colors[@]}"; do
        new_color="${colors[$old_color]}"
        # Use case-insensitive replacement
        sed -i "s/${old_color}/${new_color}/gi" "$tmp_file"
    done

    mv "$tmp_file" "$file"
    echo "Updated: $file"
}

# Backup original theme and restore before applying new colors
backup_theme
restore_from_backup

# Apply to GTK 3.0
if [[ -f "$THEME_DIR/gtk-3.0/gtk-dark.css" ]]; then
    apply_colors "$THEME_DIR/gtk-3.0/gtk-dark.css" DARK_COLORS
fi

if [[ -f "$THEME_DIR/gtk-3.0/gtk.css" ]]; then
    apply_colors "$THEME_DIR/gtk-3.0/gtk.css" LIGHT_COLORS
fi

# Apply to GTK 4.0
if [[ -f "$THEME_DIR/gtk-4.0/gtk-dark.css" ]]; then
    apply_colors "$THEME_DIR/gtk-4.0/gtk-dark.css" DARK_COLORS
fi

if [[ -f "$THEME_DIR/gtk-4.0/gtk.css" ]]; then
    apply_colors "$THEME_DIR/gtk-4.0/gtk.css" LIGHT_COLORS
fi

echo "Sweet theme colors updated!"
